version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: AutoFixture
    versions:
    - 4.15.0
    - 4.16.0
  - dependency-name: Withywoods.Net.Http
    versions:
    - 1.4.0
    - 1.4.1
  - dependency-name: Withywoods.Serialization
    versions:
    - 1.4.0
    - 1.4.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Moq
    versions:
    - 4.16.0
